name: tests-release
on:
  push:
    branches:
      - feature/*
      - master
jobs:
  run-tests:
    environment: email-password
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: true
      - run: |
          sudo apt update 
          sudo apt-get install -y cmake g++
      - run: echo "running tests."
      - run: make tests
        env:
          EMAIL: ${{  secrets.EMAIL  }}
          PASSWORD: ${{  secrets.PASSWORD  }}

